//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassTheTest
    {
        public int Id { get; set; }
        public int StudentID { get; set; }
        public int TestID { get; set; }
        public virtual Student Student { get; set; }
        public virtual Test Test { get; set; }
    }
}
