//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestQuestions
    {
        public int Id { get; set; }
        public string Question { get; set; }
        public string TrueAns { get; set; }
        public string Ans2 { get; set; }
        public string Ans3 { get; set; }
        public string Ans4 { get; set; }
        public int TestID { get; set; }
    
        public virtual Test Test { get; set; }
    }
}
